### Teste API
GET http://localhost:3003/

### Ping
GET http://localhost:3003/ping

### Get all users
http://localhost:3003/users

### Get all products
http://localhost:3003/products

### Create new user
POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u003",
    "name": "Taya",
    "email": "taya@labenu.com",
    "password": "taya123"
}

### Create new product
POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "prod003",
    "name": "Memória RAM gamer",
    "price": 470,
    "description": "Pente de memória com luz RGB, 8GB",
    "imageUrl": "https://cdn.dooca.store/1841/products/rgb-8gb.jpg?v=1658784978&webp=0"
}

### Delete user by id
DELETE http://localhost:3003/users/u001

### Delete product by id
DELETE http://localhost:3003/products/prod001

### Edit product by id
PUT http://localhost:3003/products/prod001
Content-Type: application/json

{
    "id": "id_test",
    "name": "product_name_test",
    "price": 500,
    "description": "Descrição de produto teste", 
    "imageUrl": "https://edifier.com.br/pub/media/catalog/product/m/e/mecanica-produto-teste-nao-comprar-p-1533242083167_2.jpg"
}